### ISSUE TITLE
IPTC Photo Metadata for Google Images

### ISSUE THREAD

**Issue by AbsurdePhoton** [diderich/metadata#2]
Hi,

nice job, really, I'm impressed. Your idea of not caring about the standards, focusing on the data and synchronizing them is relevant.

I have a photo website (see my signature), and I was looking for a solution to add the metada required by Google to make appear image rights in Google Image. According to [this page on iptc.org](https://iptc.org/standards/photo-metadata/quick-guide-to-iptc-photo-metadata-and-google-images/), there are two important fields to add using the IPTC 2021.1 standard:
- [Web Statement of Rights](https://iptc.org/std/photometadata/specification/IPTC-PhotoMetadata#web-statement-of-rights)
- [Licensor URL](http://ns.useplus.org/LDF/ldf-XMPSpecification#LicensorURL), a sub-field of [Licensor](https://iptc.org/std/photometadata/specification/IPTC-PhotoMetadata#licensor) (uses xmp-plus standard) - other fields in Licensor could be useful, like LicensorName or LicensorEmail, etc

Your implementation already has what it takes to add these required fields:
- Creator
- Credit Line
- Copyright Notice

So, you would make my day if you added the 2 other required structures to your library... what do you think ? :)

Regards,

AbsurdePhoton
www.absurdephoton.fr

**Comment by diderich** [comment]
I will add the **Web Statement of Rights** in an upcoming release (v1.2.1), probably by the end of August 2022.

Implementing the field(s) **Licensor/Licensor URL** would require significant refactoring of the library, as the class is currently built on the assumption that there is a _1-1_ or _1-many_ relationship between fields and data. This assumption is violated by bag structures like **Licensor**, **Location**, or **Product**. Therefore I am not planning any time soon to implement bag structures as required by the **Licensor** fields.

**Comment by AbsurdePhoton** [comment]
Hi, thank you for this quick answer. I didn't seriously read your code yet,  but I understand your concerns about the structure you used. The bag structure is a bit tricky, yes.

This guy [here](https://github.com/dchesterton/image) did implement the bag structure, but it is pretty dirty as he made custom functions just for that purpose, without really implementing an automatic structure. The code is not really maintained anymore.

For my needs, I succeeded yesterday writing Licensor metadata using his library in a pretty bad way: using a custom-handmade external .xmp file containing all the data I want. I read it and "paste" the content on an empty image after on-the-fly modifying of some of the fields that were useful for me. Per chance, modifying the other fields doesn't destroy the rest...

I'm afraid this won't work at all when I try using PHP 8 instead of 7... that's why I asked you, you're to my knowledge the only one actively maintaining a xmp PHP library for the moment.

**Comment by AbsurdePhoton** [comment]
Web Statement of Rights and PHP 8... many thanks :)
