### ISSUE TITLE
Exception on XMP write with unexpected child RDF container

### ISSUE THREAD

**Issue by rokclimb15** [diderich/metadata#3]
Running the example code with the attached image produces the following stack trace. The problem is the presence of `rdf:Bag` in the `dc:creator` rather than the expected `rdf:Seq`. Since these container elements are interchangeable, I'm going to put up a PR to make this code less rigid when deleting the child elements.

```
PHP Fatal error:  Uncaught Holiday\Metadata\Exception: Incorrect element tag found in /root/vendor/diderich/metadata/src/Metadata/XmpDocument.php:748
Stack trace:
#0 /root/vendor/diderich/metadata/src/Metadata/XmpDocument.php(302): Holiday\Metadata\XmpDocument->setXmpLiNS()
#1 /root/vendor/diderich/metadata/src/Metadata.php(984): Holiday\Metadata\XmpDocument->setXmpSeq()
```
![7664271](https://user-images.githubusercontent.com/583271/223143745-b6a31853-4e49-40c8-9369-25374c0df331.jpg)

**Comment by diderich** [comment]
Dear @rokclimb15. The Dublin standard requires the `dc:creator` to be of type `seq`, rather than `bag` as shown in the specification below:
![dc_creator](https://user-images.githubusercontent.com/10230144/223373923-db9c6714-787f-4fd1-bc10-b189d2fa772a.png)
